### ISSUE TITLE
Renaming the project from clarin-curation-module to curation-dashboard 

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/curation-dashboard#106]
The web-frontend was already renamed to curation-dashboard and we want to rename the whole project from clarin-curation-module to curation-dashboard. 
Hence version 5.2.0 is the last version under the old project. I'm going to close the project for further changes and I will create a new one under the new name

**Comment by twagoo** [comment]
It should be possible to just rename it... If you don't have the rights, an organisation admin can do it.

**Comment by wowasa** [comment]
done
