### ISSUE TITLE
Getting gateway timeouts on CMDI validation

### ISSUE THREAD

**Issue by jknappen** [clarin-eric/curation-dashboard#128]
In the course of our centre reassessment I came back to the curation dashboard. I found to my surprise that it claims issues with one of out CMDI files. Trying to validate it I got a gateway timeout.

How to reproduce: Enter one of the following URL to your browser:

https://curation.clarin.eu/curate?url-input=clarin/results/cmdi/UdS_CLARIN_D_Repository/oai_fedora_clarin_d_uni_saarland_de_clarind_uds_rsc.xml

https://curation.clarin.eu/curate?url-input=http%3A%2F%2Ffedora.clarin-d.uni-saarland.de%2Ffedora%2Fobjects%2Fclarind-uds%3Arsc%2Fdatastreams%2FCMDI%2Fcontent

Both gave me "504 Gateway Time-out" just a few minutes ago.

**Comment by wowasa** [comment]
Hi Jörg, 

I will have a look and give you a feedback by tomorrow

**Comment by wowasa** [comment]
the bug is fixed on our testserver https://alpha-curation.clarin.eu but not in production yet. 
Due to the new link checking categoy »Invalid_URL« I had to make some database fields nullable and I forgot to check for null in the processing class

**Comment by wowasa** [comment]
I'm preparing a release with a bug fix, which will be deployed to production next week. In the mean time you can do instance validation on our alpha server, if necessary. Only the linkchecker data is not up to date there. 

Thank you for reporting this bug!

**Comment by wowasa** [comment]
bug fix was deployed to production

**Comment by wowasa** [comment]
closing the issue since the bug is fixed
