### ISSUE TITLE
Validation of resource availability and type

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/curation-dashboard#15]
Much value would be added to the quality assessment if linked resources could be checked for a number of properties:
* matching actual content type at retrieval, if mime type specified in the resource proxy (or elsewhere in the metadata in a reliable way)
* retrievability in accordance with availability level, e.g. if 'PUB' all linked resources should be retrievable over HTTP with a 200 response; optionally detect login pages and/or shibboleth redirects
* general online availability: none of the resources or landing/search pages should lead to a 404, 500 or other error code (after optional redirects)

**Comment by coy123** [comment]
1) Where would the mime-type be specified in resource proxy?
2)I'm not sure what this means.
3)This one is implemented with the url-checker.

**Comment by twagoo** [comment]
@coy123:

1) See the [CMDI technical specification](https://www.clarin.eu/cmdi1.2-specification) (section 2.3.1)
2) This one is a bit tricky but it comes down the assumption that IF a record is listed in the VLO as having PUB availability level, its resources should also be directly accessible. I would leave checking for this for now though as there are various caveats.
3) 👍

**Comment by wowasa** [comment]
we mustn't forget that, in the relational database design, the same link can have different mime-types in different contexts, which might be contradictory

**Comment by wowasa** [comment]
I'm closing the issue since most of it is covered now by the link checker and the relational database design
