### ISSUE TITLE
Instance usage in profiles overview is wrong

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/curation-dashboard#151]
If we sum up all the instance usages we get an amount of less than 5000 but we're processing some hundred thousand instances. Hence either the number per profile is wrong or (what seems to be more like) some well used profiles are missing in the overview

**Comment by twagoo** [comment]
Keep in mind that there will always be an omission due to there being records based on private, unpublished profiles. This however far from fully explains the gap you describe.

**Comment by wowasa** [comment]
bug fixed in v 6.0.0
