### ISSUE TITLE
Sanitise section titles and reference labels

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/curation-dashboard#154]
**1) Remove the word 'section' from the section headings in the HTML version of the reports.**

Examples:
- File Section -> Files
- Profile Usage Section -> Profile usage
- XML Populated Section -> XML population
- etc

**2) Replace the labels in the overview table with the actual titles, or shortened versions if necessary.**

Examples:
- FileReport -> Files
- ProfileReport -> Profile usage
- etc

**Comment by wowasa** [comment]
implemented in v. 6.1.0
