### ISSUE TITLE
Score record title 'friendliness'?

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/curation-dashboard#16]
Many records have a (mapped) title that is not very descriptive or even friendly to the human reader. For example the otherwise excellent records from the Leipzig Corpora Collection have names like _ukr_newscrawl_2011_1M_ and _LCC data provider "www.elkhabar.com" in resource with identifier 11022/0000-0000-7F4F-B_ These values come from a 'name' field, there is no additional title; this would be the solution, but this issue is about identifying issues. 

I don't have an exact solution but it would be nice if the name/title, as shown in the VLO, could be scored according to some heuristic analysis that could involve the length of the title, number of characters, relative number of spaces, relative number of non-alphabetical characters. Perhaps such a measure already exists. I would not make this a big part of the overall score but it would be nice as a soft warning as part of the metadata quality report.

If I come across existing methods for scoring title quality for human readability, I will share it in a comment to this issue.

**Comment by twagoo** [comment]
Maybe it could be an interesting student project to apply text classification/language identification techniques and/or machine learning to automatically distinguish between identifier-based title and informative titles? 🙂

**Comment by wowasa** [comment]
closing this because it is rather a harvester than a curation issue, since the harvester is giving the record name the curation only takes it as it is. If we want to score the given name for user friendliness, we could do the same for the content of some fields and by doing so we're expanding curation to a level which is in no case economically justified
