### ISSUE TITLE
Better (more distinct) file names for downloads

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/curation-dashboard#163]
At the moment there is no file name in the header for the download of XML, JSON, TSV versions of reports. This leads to files with names such as `Broken.zip`.

I think it would be nice to construct a filename that encodes some context, for instance collection name and category in the case of link tables. For example the response for the link

* https://curation.clarin.eu/download/linkchecker/CLARIN_PL_digital_repository/Broken

could include a header:
```
Content-Disposition: attachment; filename="CLARIN_PL_digital_repository_Broken_ 2023-04-25_20_29_37_XML.zip"
```

Here the filename pattern is `{collection}_{category}_{query_date}_{query_time}_{format}.zip` but this is just a suggestion.

Also, as a suggestion, the file inside could have the same pattern without the `{format}` part. Right now it only has `{collection}`.

**Comment by wowasa** [comment]
but collection names can be quite long (see https://alpha-curation.clarin.eu/collection/LINDAT_CLARIAH_CZ_digital_library_at_the_Institute_of_Formal_and_Applied_Linguistics_UFAL_Faculty_of_Mathematics_and_Physics_Charles_University.html) and I suppose that the user knows for which collection he wants to download the data

**Comment by wowasa** [comment]
implemented in v. 6.1
