### ISSUE TITLE
Implementation of adapted CMDIParserVTDXML

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/curation-dashboard#176]
Implementation of the adapted CMDIParserVTDXML (see https://github.com/clarin-eric/VLO/issues/368)

**Comment by twagoo** [comment]
Quick clarification: it's not CMDIParserVTDXML that has been adapted, but there is a new CMDIRecordProcessor that should be used instead. See https://github.com/clarin-eric/VLO/blob/4.11.5-alpha1/vlo-importer/src/main/java/eu/clarin/cmdi/vlo/importer/CMDIRecordProcessor.java#L87

**Comment by wowasa** [comment]
implemented in v. 6.1.0
