### ISSUE TITLE
Disable ZIP containers for TSV dow

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/curation-dashboard#195]
Eg https://curation.clarin.eu/download/linkchecker/ARCHE/Broken?format=tsv delivers a zip file with a TSV inside. This prevents external consumers (eg google sheets) to import the TSV directly. Would be good to drop the zip and offer TSV directly. The on-the-fly compression by the webserver should help to keep things efficient.

**Comment by twagoo** [comment]
and we could perhaps still offer `tsv.zip` as an alternative format option

**Comment by wowasa** [comment]
double with #196
