### ISSUE TITLE
BeanCreationException for FacetsMappingCacheFactory

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/curation-dashboard#214]
FacetMappingCacheFactory can't be instantiated. 

The error occurs when the DefaultVloConfigFactory is used, which is the case when the property curation.vlo_config_location is not set. 
Apparently there is a code change in vlo-commons, since the default VloConfig.xml has some empty elements like »facetConceptsFile«, which have to be set to default values now by calling  DefaultVloConfigFactory.configureDefaultMappingLocations(VloConfig config)

**Comment by twagoo** [comment]
Does this affect curation at runtime or in some other context (e.g. tests)? It would be helpful if you could indicate the version numbers of vlo-commons before and after this regression occurred. With this information I can look at potential causes of the issue in the VLO.

**Comment by wowasa** [comment]
fixed for v. 6.3.0

it has no effect on the running software, since we don't use the DefaultVloConfigFactory there
