### ISSUE TITLE
Update concept registry API call

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/curation-dashboard#216]
The concept registry API which we call in the CCR has changed. We need to adapt the call. Further on we have to assure that the API is not called for any file in case of an exception. Maybe we should throw a RuntimeException but we have to make sure then that this doesn't prevent the start of curation-web, where the ccr service is only required in case of an instance/profile analysis.

**Comment by twagoo** [comment]
Some essential information about the new API. The [new concept registry](https://vocabularies.clarin.eu/clavas/ccr/en/) is based on [Skosmos](https://github.com/NatLibFi/Skosmos). 

There exists [written documentation for the Skosmos REST API](https://github.com/NatLibFi/Skosmos/wiki/REST-API) and the [interactive Swagger for the Finto instance](http://api.finto.fi/doc/) is also helpful.

Important calls for the concept registry with examples:
* Base URL that should be configurable: `https://vocabularies.clarin.eu/clavas/rest/v1`
* Getting a specific concept `https://vocabularies.clarin.eu/clavas/rest/v1/data?uri={urlEncode(conceptUri)}` – response as SKOS XML, 
  * Example: https://vocabularies.clarin.eu/clavas/rest/v1/data?uri=http%3A%2F%2Fhdl.handle.net%2F11459%2FCCR_C-4541_6dc2d021-1811-3d05-56ca-7ef3e394817c%20
* Getting all concepts: could be a bit tricky, let me know if you need this

**Comment by wowasa** [comment]
it's not really a need but if curation can't get all concepts at one each run of update dashboard will fire some hundred requests within a few minutes. Further on each user profile/cmd instance upload in the web-interface fires dozens of requests

**Comment by twagoo** [comment]
Best documented way to get *all* concepts in a vocabulary, i.e. in the entire concept registry is by making an initial call
* `{baseUrl}/{vocab}/index/` where `{vocab}` is `ccr` but this should be configurable along with the base URL.
  * Example: https://vocabularies.clarin.eu/clavas/rest/v1/ccr/index/
  * Note: the response is JSON-LD and is best processed as such!! Literal paths are brittle
* then for each `{letter}` in the list `skosmos:indexLetters` call `{baseUrl}/{vocab}/index/{letter}`
  * Example: https://vocabularies.clarin.eu/clavas/rest/v1/ccr/index/A

Note: it could be that there may be duplicates in the list??

**Comment by wowasa** [comment]
done

**Comment by twagoo** [comment]
Thanks for the quick implementation.
Can we make a follow-up ticket that covers making the SAX parsing namespace aware and rather than use prefix assumptions? This would make it much more robust even though it should be ok for the short term.

**Comment by twagoo** [comment]
And/or perhaps use an xpath based approach, seems more robust as well.

**Comment by wowasa** [comment]
> Thanks for the quick implementation. Can we make a follow-up ticket that covers making the SAX parsing namespace aware rather than use prefix assumptions? This would make it much more robust even though it should be ok for the short term.

done
