### ISSUE TITLE
Adapt link to concept in profile report view

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/curation-dashboard#217]
In the html view the link to the concept definition must not be the concept URI anymore but 
`https://vocabularies.clarin.eu/clavas/ccr/en/page/?uri=<concept URI>`

**Comment by twagoo** [comment]
It should in fact be the concept URI! They are temporarily broken (handles still resolve to the old OpenSKOS locations) but @menzowindhouwer has this on his TODO list if I'm not mistaken!

**Comment by wowasa** [comment]
ok - in this case I'm resetting it to the previous version
