### ISSUE TITLE
More prominent link to CLARIN curation dashboard

### ISSUE THREAD

**Issue by TomazErjavec** [clarin-eric/curation-dashboard#229]
I would suggest a minor edit to the main README, namley that the https://curation.clarin.eu/ gets a more prominent place at the start of the readme - now it is semi-hidden at the very end, rather than being the first link, as it is the "public facing" aspect of this GitHub repository.

**Comment by wowasa** [comment]
actually I think it's an academic discussion if it should be bottom up or top down. But I changed the order anyway. It's in the dev branch now and I will push it to main branch as soon as the 6.4.0 release is ready
