### ISSUE TITLE
Add link to general collection report in collection specific linkchecker report

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/curation-dashboard#230]
For instance add a link to <https://curation.clarin.eu/collection/CLARIN_PL_digital_repository.html> from <https://curation.clarin.eu/linkchecker/CLARIN_PL_digital_repository>. The name of the "collection" could be the link. 

For example:

> # Linkchecker Detail Report
> ## Collection name: [CLARIN PL digital repository](https://curation.clarin.eu/collection/CLARIN_PL_digital_repository.html)
> ### Category: Ok

**Comment by wowasa** [comment]
implemented in 6.4.0. »Overall« is pointing to the collection overview
