### ISSUE TITLE
processing accept header for reports

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/curation-dashboard#251]
All reports should be downloadable in the so far provided formats xml, json and tsv not only by download URL but also by view URL with accept header. For example <host>/collection shows an html view of the overview table, the same URL with an accept header text/xml or application/xml should provide the table in xml format

**Comment by twagoo** [comment]
Suggestion: perhaps this should be a new URL. The existing URL formats could be implemented as a redirect to the new URL a parameter that forces the format (ignoring any accept headers as before). This way users of the old URLs will never get unexpected results.

**Comment by wowasa** [comment]
implemented
