### ISSUE TITLE
Use _metadataDirectory field to link to "collection" in the VLO

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/curation-dashboard#254]
This is a follow-up of #13.

Since https://github.com/clarin-eric/VLO/issues/375 implements the addition of a `_metadataDirectory` field, links using `_fileName` with wildcards can now be replaced with a link that defines a more precise query.

For example, the link found at https://curation.clarin.eu/collection/The_Language_Archive.html:
- [`https://vlo.clarin.eu/search?q=_fileName:*clarin/results/cmdi/The_Language_Archive*`](https://vlo.clarin.eu/search?q=_fileName:*clarin/results/cmdi/The_Language_Archive*)

Can be replaced with
- [`https://vlo.clarin.eu/search?q=_metadataDirectory:clarin/results/cmdi/The_Language_Archive`](https://vlo.clarin.eu/search?q=_metadataDirectory:clarin/results/cmdi/The_Language_Archive)
- (**or more correctly the URL encoded version:** `https://vlo.clarin.eu/search?q=_metadataDirectory%3Aclarin%2Fresults%2Fcmdi%2FThe_Language_Archive`)

**Note: these links will not work until this feature has been promoted to production**, but in the meantime it can be tested in [beta](https://beta-vlo.clarin.eu/search?q=_metadataDirectory%3Aclarin%2Fresults%2Fcmdi%2FThe_Language_Archive).

**Comment by wowasa** [comment]
changed stylesheet in separate issue_254 branch for it

**Comment by twagoo** [comment]
Looks good but if you have the ability it would be good to do at least some basic URL encoding. If available, this should do the job: https://www.oreilly.com/library/view/xslt-2nd-edition/9780596527211/re86.html

**Comment by wowasa** [comment]
merged to java21 branch
