### ISSUE TITLE
redirect /collection/AllCollectionReport to /collection/AllCollectionReport.html

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/curation-dashboard#261]
an explicit requirement from our September 25th meeting was to redirect a call to /collection/AllCollectionReport to /collection/AllCollectionReport.html. I make it more general:

- any html report should be callable with and without .html suffix
- if a report doesn't exist under the given name, the response must return a status code 404 instead of 500

**Comment by twagoo** [comment]
For the record, redirect `/collection/AllCollectionReport` to `/collection/AllCollectionReport.html` IFF HTML is requested via the Accept header. In the case of JSON, XML, TSV I think the response should be in the requested format without a redirect.

**Comment by wowasa** [comment]
implemented
