### ISSUE TITLE
Show link checking history information

### ISSUE THREAD

**Issue by coy123** [clarin-eric/curation-dashboard#57]
Find a usage for the history table. Maybe to the history of each link, when clicked on, in the linkchecker statistics page.

**Comment by coy123** [comment]
On the url table SHOW button should trigger a query into the history table in the database. It should fill then a smaller table next to the info. See screenshot.
![Screenshot from 2020-03-06 12-29-13](https://user-images.githubusercontent.com/2759147/100454137-9a8f4e80-30bc-11eb-9aa9-73b3e2467e27.png)

**Comment by twagoo** [comment]
Pruning of history table after a year -> #164

**Comment by wowasa** [comment]
I'm doubting that anybody wants to have this in the detail view for a certain link. Now where we have increased the speed of link checking significantly, we should rather think of way to display a time line either by collection or by host, to show the reliability at a glance

**Comment by wowasa** [comment]
the issue is obsolete by decision and replaced by issue #233
