### ISSUE TITLE
Unit and Integration Tests

### ISSUE THREAD

**Issue by coy123** [clarin-eric/curation-dashboard#65]
There should be a lot more tests than there is right now.
One idea to do regression testing is the create reports and save them in test/resources folder. Then whenever a new change is made, the test would generate new reports from the same source and compare it to the saved report to see what changed and if the change was intended.

**Comment by twagoo** [comment]
End-to-end testing in [https://gitlab.com/CLARIN-ERIC/compose_curation](compose_curation)
