### ISSUE TITLE
Overview of last linkchecker status results

### ISSUE THREAD

**Issue by wowasa** [clarin-eric/curation-dashboard#97]
the web application should show the latest x link checking results

**Comment by wowasa** [comment]
my suggestion is to have a table with the last 50 results: only URL and category with background-color depending on category and a detail view as in the linkchechecker statistics

**Comment by twagoo** [comment]
Perhaps this information could be 'pushed' rather than pulled. The linkchecking process "logs" the last checked URL with its findings to some destination that is being rotated, only keeping the last X entries. This then is somehow shown in the dashboard.

**Comment by wowasa** [comment]
thymeleaf provides us the mean to include easily the text of one file into an HTML page

**Comment by twagoo** [comment]
* Make a dedicated page for it
* Link to the page from the linkchecker report
* Show the 100 last checked links

**Comment by wowasa** [comment]
implemented in v. 6.1.0
